<?xml version="1.0"?>
<robot name="physics" xmlns:xacro="http://ros.org/wiki/xacro">
    <gazebo reference="base_link">
    </gazebo>
    <!-- 属性封装 -->
    <xacro:property name="base_footprint_radius" value="0.001" /> <!-- base_footprint 半径  -->
    <material name="blue">
        <color rgba="0 0 0.8 1"/>
      </material>
      <material name="black">
        <color rgba="0 0 0 1"/>
      </material>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
  <!-- 圆柱惯性矩阵 -->
    <xacro:macro name="cylinder_inertial_matrix" params="m r h">
        <inertial>
            <mass value="${m}" />
            <inertia ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
                iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
                izz="${m*r*r/2}" /> 
        </inertial>
    </xacro:macro>
    <!-- 立方体惯性矩阵 -->
    <xacro:macro name="Box_inertial_matrix" params="m l w h">
       <inertial>
               <mass value="${m}" />
               <inertia ixx="${m*(h*h + l*l)/12}" ixy = "0" ixz = "0"
                   iyy="${m*(w*w + l*l)/12}" iyz= "0"
                   izz="${m*(w*w + h*h)/12}" />
       </inertial>
   </xacro:macro>


      </material>
    <!-- 车身属性 -->
    <xacro:property name="bodywidth" value="0.15" />
    <xacro:property name="bodylen" value="0.25" />
    <xacro:property name="bodyheight" value="0.05" />
    <xacro:property name="earth_space" value="0.015" /> <!-- 离地间距 -->
    <xacro:property name="PI" value="3.1415927" />

    <!-- 宏 -->
    <!-- 底盘 -->
    <link name="base_footprint">
        <visual>
            <geometry>
            <sphere radius="${base_footprint_radius}" />
            </geometry>
        </visual>
        </link>
      <!-- 车身 -->
      <link name="base_link">
        <visual>
          <geometry>
            <box size="${bodylen} ${bodywidth} ${bodyheight}"/>
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <material name="blue"/>
        </visual>
        <collision>
          <geometry>
              <box size="${bodylen} ${bodywidth} ${bodyheight}"/>
          </geometry>
      </collision>
      <xacro:Box_inertial_matrix m="5" l="${bodylen}" w="${bodywidth}" h="${bodyheight}"/>
      </link>
      <joint name="base_link2base_footprint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${earth_space + bodyheight / 2 }" />
      </joint>
      <!-- 车轮 -->
    <!-- 车轮属性 -->
    <xacro:property name="wheel_radius" value="0.0375" />
    <xacro:property name="wheel_length" value="0.02" />
    <!-- 轮宏实现 -->
    <xacro:macro name="add_wheels" params="name flag">
        <link name="${name}_wheel">
          <visual>
            <geometry>
              <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="${PI / 2} 0.0 0.0" />
            <material name="black" />
          </visual>
          <collision>
            <geometry>
                <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertial_matrix m="5" r="${wheel_radius}" h="${wheel_length}"/>

        </link>
        <joint name="${name}_wheel2base_link" type="continuous">
            <parent link="base_link" />
            <child link="${name}_wheel" />
            <origin xyz="0 ${flag * (bodywidth/2+wheel_length/2)} ${-(earth_space + bodyheight / 2 - wheel_radius) }" />
            <axis xyz="0 1 0" />
          </joint>
        </xacro:macro>
        <xacro:add_wheels name="left" flag="1" />
        <xacro:add_wheels name="right" flag="-1" />
        <!-- 传感器属性 -->
        <xacro:property name="gps_len" value="0.03" />
        <xacro:property name="imu_len" value="0.01" />
        <xacro:property name="imu_width" value="0.02" />
        <!-- 传感器宏实现 -->
        <xacro:macro name="add_sensor" params="name lenth width flag">
            <link name="${name}_link">
                <visual>
                  <geometry>
                    <box size="${lenth} ${width} 0.004"/>
                  </geometry>
                  <material name="yellow"/>
                </visual>
                <collision>
                  <geometry>
                    <box size="${lenth} ${width} 0.004"/>
                  </geometry>
              </collision>
              <xacro:Box_inertial_matrix m="0.2" l="${lenth}" w="${width}" h="0.004"/>
              </link>
            <joint name="${name}_sensor2base_link" type="fixed">
            <parent link="base_link" />
            <child link="${name}_link" />
            <origin xyz="0 ${flag*0.03} ${bodyheight/2}" />
            <axis xyz="0 0 0" />
            </joint>
        </xacro:macro>
        <xacro:add_sensor name="gps" lenth="${gps_len}" width="${gps_len}" flag="-1"/>
        <xacro:add_sensor name="imu" lenth="${imu_len}" width="${imu_width}" flag="1"/>
        <!-- 超声波 -->
      <link name="sonar_link">
        <visual>
          <geometry>
            <box size="0.02 0.05 0.001"/>
          </geometry>
          <origin xyz="0 0 0" rpy="0 ${PI/2} 0" />
          <material name="white"/>
        </visual>
        <collision>
          <geometry>
            <box size="0.02 0.05 0.001"/>
          </geometry>
      </collision>
      <xacro:Box_inertial_matrix m="0.5" l="0.02" w="0.05" h="0.001"/>
      </link>
      <joint name="sonar_link2base_link" type="fixed">
        <parent link="base_link" />
        <child link="sonar_link" />
        <origin xyz="${bodylen/2 - 0.001} 0 ${earth_space + bodyheight / 2 }" />
      </joint>

</robot>
